[tool.ruff]
line-length = 130

exclude = [
    # "utils/slicer.py",
    # "utils/propagate_aortic_annotation.py"
    # "utils/ukb_field_categories.py",
    # "utils/execute.py",
    # "utils/download_data_ukbb_general.py",
    # "utils/convert_data_ukbb2964.py",
    # "src/segmentation",    
    # "src/registration/",
    ".git",
    ".github",
    "archive",
    "code",
    "data",
    "doc",
    "lib",
    "model",
    "tasks",
    "temp",
    "third_party"
]

[tool.ruff.lint]
preview = true  # so that some rules can be enabled
select = ["E", "F"]  # Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default
extend-select = ["W391"]