[tool.ruff]
line-length = 120

[tool.ruff.lint]
preview = true  # so that some rules can be enabled
select = ["E", "F"]  # Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default
extend-select = ["W391"]

# todo 'common','util' and 'src' need to be completed in the future
exclude = [
    "common", 
    "utils",
    "src/segmentation/",
    "src/feature_extraction/aortic/",    
    "src/registration/",
    ".git",
    "archive",
    "data",
    "doc",
    "others",
    "par",
    "test",
    "third_party",
    "model",
    "others"
]